default_language_version:
    python: python3.10
repos:
-   repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: python3 -m ruff check . --fix
        language: system
        always_run: true
        pass_filenames: false